/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type CtaSection = {
  _type: "ctaSection";
  heading?: string;
  highlightedText?: string;
  description?: string;
  button?: {
    label?: string;
    href?: string;
  };
};

export type CtaCard = {
  _type: "ctaCard";
  heading?: string;
  description?: string;
  button?: {
    label?: string;
    href?: string;
  };
};

export type OurMission = {
  _type: "ourMission";
  eyebrow?: string;
  heading?: string;
  description?: string;
  button?: {
    label?: string;
    href?: string;
  };
};

export type HeroSimple = {
  _type: "heroSimple";
  eyebrow?: string;
  heading?: string;
  description?: string;
  button?: {
    label?: string;
    href?: string;
  };
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  content?: PageBuilder;
};

export type PageBuilder = Array<{
  _key: string;
} & HeroSimple | {
  _key: string;
} & OurMission | {
  _key: string;
} & CtaSection>;

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Process = {
  _id: string;
  _type: "process";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  order?: number;
  description?: string;
  icon?: "Search" | "FlaskConical" | "Scale" | "ShieldCheck" | "RefreshCw" | "CheckCircle" | "Zap" | "Target" | "Heart" | "Star" | "Leaf" | "Lightbulb";
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  popular?: boolean;
  excerpt?: string;
  type?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "articleType";
  };
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  featuredImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  productGallery?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  }>;
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  tags?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "tag";
  }>;
  publishedAt?: string;
  body?: BlockContent;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    linkType?: "internal" | "external";
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  label?: string;
  url?: string;
  variant?: "primary" | "secondary" | "outline";
  alignment?: "left" | "center" | "right";
  openInNewTab?: boolean;
  _type: "button";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
  _key: string;
} | {
  type?: "youtube" | "vimeo" | "custom";
  url?: string;
  caption?: string;
  aspectRatio?: "16/9" | "4/3" | "1/1" | "auto";
  _type: "embed";
  _key: string;
}>;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type ArticleType = {
  _id: string;
  _type: "articleType";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Tag = {
  _id: string;
  _type: "tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = CtaSection | CtaCard | OurMission | HeroSimple | Page | PageBuilder | Slug | Process | Article | BlockContent | SanityImageCrop | SanityImageHotspot | Author | ArticleType | Tag | Category | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: lib/queries.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0] {    _id,    _type,    content  }
export type PAGE_QUERYResult = {
  _id: string;
  _type: "page";
  content: PageBuilder | null;
} | null;
// Variable: GET_RECENT_ARTICLES_QUERY
// Query: *[_type == "article" && defined(publishedAt)] | order(publishedAt desc)[0...20] {    _id,    title,    "slug": slug.current,    excerpt,    popular,    body,    type->{      title,      "slug": slug.current    },    publishedAt,    _updatedAt,    featuredImage {      alt,      "url": asset->url    },    categories[]-> {      title,      "slug": slug.current    },    tags[]-> {      title,      "slug": slug.current    },    productGallery[] {      alt,      "url": asset->url    },    author-> {      name    }  }
export type GET_RECENT_ARTICLES_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  popular: boolean | null;
  body: BlockContent | null;
  type: {
    title: string | null;
    slug: string | null;
  } | null;
  publishedAt: string;
  _updatedAt: string;
  featuredImage: {
    alt: string | null;
    url: string | null;
  } | null;
  categories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
  tags: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
  productGallery: Array<{
    alt: string | null;
    url: string | null;
  }> | null;
  author: {
    name: string | null;
  } | null;
}>;
// Variable: GET_POPULAR_ARTICLES_QUERY
// Query: *[_type == "article" && popular == true && defined(publishedAt)]  | order(publishedAt desc)[0...6] {    _id,    title,    "slug": slug.current,    excerpt,    popular,    body,    type->{      title,      "slug": slug.current    },    publishedAt,    _updatedAt,    featuredImage {      alt,      "url": asset->url    },    categories[]->{      title,      "slug": slug.current    }  }
export type GET_POPULAR_ARTICLES_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  popular: true;
  body: BlockContent | null;
  type: {
    title: string | null;
    slug: string | null;
  } | null;
  publishedAt: string;
  _updatedAt: string;
  featuredImage: {
    alt: string | null;
    url: string | null;
  } | null;
  categories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
}>;
// Variable: GET_RELATED_ARTICLES_QUERY
// Query: *[    _type == "article" &&    slug.current != $slug &&    (      count((categories[]->slug.current)[@ in $categorySlugs]) > 0     )  ]  | order(publishedAt desc)[0...4] {    _id,    title,    "slug": slug.current,    excerpt,    popular,    body,    type->{      title,      "slug": slug.current    },    publishedAt,    featuredImage {      alt,      "url": asset->url    },    categories[]->{      title,      "slug": slug.current    }  }
export type GET_RELATED_ARTICLES_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  popular: boolean | null;
  body: BlockContent | null;
  type: {
    title: string | null;
    slug: string | null;
  } | null;
  publishedAt: string | null;
  featuredImage: {
    alt: string | null;
    url: string | null;
  } | null;
  categories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
}>;
// Variable: GET_ARTICLE_BY_SLUG_QUERY
// Query: *[_type == "article" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    excerpt,    popular,    body,    publishedAt,    _updatedAt,    type->{      title,"slug": slug.current    },    content, // Often needed for the full page    categories[]-> {      title,      "slug": slug.current    },    tags[]-> {      title,      "slug": slug.current    },    featuredImage {      alt,      "url": asset->url    },    productGallery[] {      alt,      "url": asset->url    },    author-> {      name,      bio,      "image": image.asset->url    }  }
export type GET_ARTICLE_BY_SLUG_QUERYResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  popular: boolean | null;
  body: BlockContent | null;
  publishedAt: string | null;
  _updatedAt: string;
  type: {
    title: string | null;
    slug: string | null;
  } | null;
  content: null;
  categories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
  tags: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
  featuredImage: {
    alt: string | null;
    url: string | null;
  } | null;
  productGallery: Array<{
    alt: string | null;
    url: string | null;
  }> | null;
  author: {
    name: string | null;
    bio: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    image: string | null;
  } | null;
} | null;
// Variable: GET_ARTICLES_BY_CATEGORY_QUERY
// Query: *[_type == "article" && references(*[_type == "category" && slug.current == $categorySlug]._id)] | order(publishedAt desc) {    _id,    title,    "slug": slug.current,    excerpt,    popular,    body,    type->{      title,"slug": slug.current    },    publishedAt,    _updatedAt,    featuredImage {      alt,      "url": asset->url    },    categories[]-> {      title,      "slug": slug.current    },    tags[]-> {      title,      "slug": slug.current    },    productGallery[] {      alt,      "url": asset->url    },    author-> {      name    }  }
export type GET_ARTICLES_BY_CATEGORY_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  popular: boolean | null;
  body: BlockContent | null;
  type: {
    title: string | null;
    slug: string | null;
  } | null;
  publishedAt: string | null;
  _updatedAt: string;
  featuredImage: {
    alt: string | null;
    url: string | null;
  } | null;
  categories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
  tags: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
  productGallery: Array<{
    alt: string | null;
    url: string | null;
  }> | null;
  author: {
    name: string | null;
  } | null;
}>;
// Variable: GET_ARTICLES_BY_TAG_QUERY
// Query: *[_type == "article" && references(*[_type == "tag" && slug.current == $tagSlug]._id)] | order(publishedAt desc) {    _id,    title,    "slug": slug.current,    excerpt,    popular,    body,    type->{      title,      "slug": slug.current    },    publishedAt,    _updatedAt,    featuredImage {      alt,      "url": asset->url    },    categories[]-> {      title,      "slug": slug.current    },    tags[]-> {      title,      "slug": slug.current    },    author-> {      name    }  }
export type GET_ARTICLES_BY_TAG_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  popular: boolean | null;
  body: BlockContent | null;
  type: {
    title: string | null;
    slug: string | null;
  } | null;
  publishedAt: string | null;
  _updatedAt: string;
  featuredImage: {
    alt: string | null;
    url: string | null;
  } | null;
  categories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
  tags: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
  author: {
    name: string | null;
  } | null;
}>;
// Variable: GET_ARTICLES_BY_TYPE_QUERY
// Query: *[_type == "article" && references(*[_type == "articleType" && slug.current == $articleTypeSlug]._id)] | order(publishedAt desc) {    _id,    title,    "slug": slug.current,    excerpt,    popular,    body,    type->{      title,      "slug": slug.current    },    publishedAt,    _updatedAt,    featuredImage {      alt,            "url": asset->url    },    categories[]-> {      title,      "slug": slug.current    },    tags[]-> {      title,      "slug": slug.current    },    author-> {      name    }  }
export type GET_ARTICLES_BY_TYPE_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  popular: boolean | null;
  body: BlockContent | null;
  type: {
    title: string | null;
    slug: string | null;
  } | null;
  publishedAt: string | null;
  _updatedAt: string;
  featuredImage: {
    alt: string | null;
    url: string | null;
  } | null;
  categories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
  tags: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
  author: {
    name: string | null;
  } | null;
}>;
// Variable: GET_ALL_CATEGORIES_QUERY
// Query: *[_type == "category"] | order(title asc) {    _id,    title,    "slug": slug.current,    description,    "imageUrl": image.asset->url,    "articleCount": count(*[_type == "article" && references(^._id)]),    _updatedAt,  }
export type GET_ALL_CATEGORIES_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  imageUrl: string | null;
  articleCount: number;
  _updatedAt: string;
}>;
// Variable: GET_CATEGORY_BY_SLUG_QUERY
// Query: *[_type == "category" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    description,    "imageUrl": image.asset->url,    "articleCount": count(*[_type == "article" && references(^._id)]),    _updatedAt,  }
export type GET_CATEGORY_BY_SLUG_QUERYResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  imageUrl: string | null;
  articleCount: number;
  _updatedAt: string;
} | null;
// Variable: GET_ALL_TAGS_QUERY
// Query: *[_type == "tag"] | order(title asc) {    _id,    title,    "slug": slug.current,    description,    "articleCount": count(*[_type == "article" && references(^._id)]),    _updatedAt,  }
export type GET_ALL_TAGS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  articleCount: number;
  _updatedAt: string;
}>;
// Variable: SITEMAP_DATA_QUERY
// Query: *[_type in ["article", "category"] && (_type == "category" || defined(publishedAt))] {    _type,    "slug": slug.current,    _updatedAt,    ...select(      _type == "article" => {        "categorySlug": categories[0]->slug.current      }    )  }
export type SITEMAP_DATA_QUERYResult = Array<{
  _type: "article";
  slug: string | null;
  _updatedAt: string;
  categorySlug: string | null;
} | {
  _type: "category";
  slug: string | null;
  _updatedAt: string;
}>;
// Variable: GET_ALL_PROCESSES_QUERY
// Query: *[_type == "process"] | order(order asc) {    _id,    title,    description,    icon,    order,  }
export type GET_ALL_PROCESSES_QUERYResult = Array<{
  _id: string;
  title: string | null;
  description: string | null;
  icon: "CheckCircle" | "FlaskConical" | "Heart" | "Leaf" | "Lightbulb" | "RefreshCw" | "Scale" | "Search" | "ShieldCheck" | "Star" | "Target" | "Zap" | null;
  order: number | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"page\" && slug.current == $slug][0] {\n    _id,\n    _type,\n    content\n  }\n": PAGE_QUERYResult;
    "  *[_type == \"article\" && defined(publishedAt)] | order(publishedAt desc)[0...20] {\n    _id,\n    title,\n    \"slug\": slug.current,\n    excerpt,\n    popular,\n    body,\n    type->{\n      title,\n      \"slug\": slug.current\n    },\n    publishedAt,\n    _updatedAt,\n    featuredImage {\n      alt,\n      \"url\": asset->url\n    },\n    categories[]-> {\n      title,\n      \"slug\": slug.current\n    },\n    tags[]-> {\n      title,\n      \"slug\": slug.current\n    },\n    productGallery[] {\n      alt,\n      \"url\": asset->url\n    },\n    author-> {\n      name\n    }\n  }": GET_RECENT_ARTICLES_QUERYResult;
    "\n  *[_type == \"article\" && popular == true && defined(publishedAt)]\n  | order(publishedAt desc)[0...6] {\n    _id,\n    title,\n    \"slug\": slug.current,\n    excerpt,\n    popular,\n    body,\n    type->{\n      title,\n      \"slug\": slug.current\n    },\n    publishedAt,\n    _updatedAt,\n    featuredImage {\n      alt,\n      \"url\": asset->url\n    },\n    categories[]->{\n      title,\n      \"slug\": slug.current\n    }\n  }\n": GET_POPULAR_ARTICLES_QUERYResult;
    "\n  *[\n    _type == \"article\" &&\n    slug.current != $slug &&\n    (\n      count((categories[]->slug.current)[@ in $categorySlugs]) > 0 \n    )\n  ]\n  | order(publishedAt desc)[0...4] {\n    _id,\n    title,\n    \"slug\": slug.current,\n    excerpt,\n    popular,\n    body,\n    type->{\n      title,\n      \"slug\": slug.current\n    },\n    publishedAt,\n    featuredImage {\n      alt,\n      \"url\": asset->url\n    },\n    categories[]->{\n      title,\n      \"slug\": slug.current\n    }\n  }\n": GET_RELATED_ARTICLES_QUERYResult;
    "  *[_type == \"article\" && slug.current == $slug][0] {\n    _id,\n    title,\n    \"slug\": slug.current,\n    excerpt,\n    popular,\n    body,\n    publishedAt,\n    _updatedAt,\n    type->{\n      title,\"slug\": slug.current\n    },\n    content, // Often needed for the full page\n    categories[]-> {\n      title,\n      \"slug\": slug.current\n    },\n    tags[]-> {\n      title,\n      \"slug\": slug.current\n    },\n    featuredImage {\n      alt,\n      \"url\": asset->url\n    },\n    productGallery[] {\n      alt,\n      \"url\": asset->url\n    },\n    author-> {\n      name,\n      bio,\n      \"image\": image.asset->url\n    }\n  }": GET_ARTICLE_BY_SLUG_QUERYResult;
    "  *[_type == \"article\" && references(*[_type == \"category\" && slug.current == $categorySlug]._id)] | order(publishedAt desc) {\n    _id,\n    title,\n    \"slug\": slug.current,\n    excerpt,\n    popular,\n    body,\n    type->{\n      title,\"slug\": slug.current\n    },\n    publishedAt,\n    _updatedAt,\n    featuredImage {\n      alt,\n      \"url\": asset->url\n    },\n    categories[]-> {\n      title,\n      \"slug\": slug.current\n    },\n    tags[]-> {\n      title,\n      \"slug\": slug.current\n    },\n    productGallery[] {\n      alt,\n      \"url\": asset->url\n    },\n    author-> {\n      name\n    }\n  }": GET_ARTICLES_BY_CATEGORY_QUERYResult;
    "  *[_type == \"article\" && references(*[_type == \"tag\" && slug.current == $tagSlug]._id)] | order(publishedAt desc) {\n    _id,\n    title,\n    \"slug\": slug.current,\n    excerpt,\n    popular,\n    body,\n    type->{\n      title,\n      \"slug\": slug.current\n    },\n    publishedAt,\n    _updatedAt,\n    featuredImage {\n      alt,\n      \"url\": asset->url\n    },\n    categories[]-> {\n      title,\n      \"slug\": slug.current\n    },\n    tags[]-> {\n      title,\n      \"slug\": slug.current\n    },\n    author-> {\n      name\n    }\n  }": GET_ARTICLES_BY_TAG_QUERYResult;
    "  *[_type == \"article\" && references(*[_type == \"articleType\" && slug.current == $articleTypeSlug]._id)] | order(publishedAt desc) {\n    _id,\n    title,\n    \"slug\": slug.current,\n    excerpt,\n    popular,\n    body,\n    type->{\n      title,\n      \"slug\": slug.current\n    },\n    publishedAt,\n    _updatedAt,\n    featuredImage {\n      alt,\n            \"url\": asset->url\n\n    },\n    categories[]-> {\n      title,\n      \"slug\": slug.current\n    },\n    tags[]-> {\n      title,\n      \"slug\": slug.current\n    },\n    author-> {\n      name\n    }\n  }": GET_ARTICLES_BY_TYPE_QUERYResult;
    "  *[_type == \"category\"] | order(title asc) {\n    _id,\n    title,\n    \"slug\": slug.current,\n    description,\n    \"imageUrl\": image.asset->url,\n    \"articleCount\": count(*[_type == \"article\" && references(^._id)]),\n    _updatedAt,\n  }": GET_ALL_CATEGORIES_QUERYResult;
    "  *[_type == \"category\" && slug.current == $slug][0] {\n    _id,\n    title,\n    \"slug\": slug.current,\n    description,\n    \"imageUrl\": image.asset->url,\n    \"articleCount\": count(*[_type == \"article\" && references(^._id)]),\n    _updatedAt,\n  }": GET_CATEGORY_BY_SLUG_QUERYResult;
    "  *[_type == \"tag\"] | order(title asc) {\n    _id,\n    title,\n    \"slug\": slug.current,\n    description,\n    \"articleCount\": count(*[_type == \"article\" && references(^._id)]),\n    _updatedAt,\n  }": GET_ALL_TAGS_QUERYResult;
    "\n  *[_type in [\"article\", \"category\"] && (_type == \"category\" || defined(publishedAt))] {\n    _type,\n    \"slug\": slug.current,\n    _updatedAt,\n    ...select(\n      _type == \"article\" => {\n        \"categorySlug\": categories[0]->slug.current\n      }\n    )\n  }\n": SITEMAP_DATA_QUERYResult;
    "\n  *[_type == \"process\"] | order(order asc) {\n    _id,\n    title,\n    description,\n    icon,\n    order,\n  }\n": GET_ALL_PROCESSES_QUERYResult;
  }
}
