/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  type?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "articleType";
  };
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  featuredImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  productGallery?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  }>;
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  tags?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "tag";
  }>;
  publishedAt?: string;
  body?: BlockContent;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    linkType?: "internal" | "external";
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  label?: string;
  url?: string;
  variant?: "primary" | "secondary" | "outline";
  alignment?: "left" | "center" | "right";
  openInNewTab?: boolean;
  _type: "button";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
  _key: string;
} | {
  type?: "youtube" | "vimeo" | "custom";
  url?: string;
  caption?: string;
  aspectRatio?: "16/9" | "4/3" | "1/1" | "auto";
  _type: "embed";
  _key: string;
}>;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type ArticleType = {
  _id: string;
  _type: "articleType";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Tag = {
  _id: string;
  _type: "tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Article | BlockContent | SanityImageCrop | SanityImageHotspot | Author | Slug | ArticleType | Tag | Category | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: lib/queries.ts
// Variable: GET_RECENT_ARTICLES_QUERY
// Query: *[_type == "article" && defined(publishedAt)] | order(publishedAt desc)[0...20] {    _id,    title,    "slug": slug.current,    excerpt,    publishedAt,    featuredImage {      alt,      "url": asset->url    },    categories[]-> {      title,      "slug": slug.current    },    productGallery[] {      alt,      "url": asset->url    },    author-> {      name    }  }
export type GET_RECENT_ARTICLES_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string;
  featuredImage: {
    alt: string | null;
    url: string | null;
  } | null;
  categories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
  productGallery: Array<{
    alt: string | null;
    url: string | null;
  }> | null;
  author: {
    name: string | null;
  } | null;
}>;
// Variable: GET_ARTICLE_BY_SLUG_QUERY
// Query: *[_type == "article" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    excerpt,    publishedAt,    content, // Often needed for the full page    categories[]-> {      title,      "slug": slug.current    },    featuredImage {      alt,      "url": asset->url    },    productGallery[] {      alt,      "url": asset->url    },    author-> {      name,      bio,      "image": image.asset->url    }  }
export type GET_ARTICLE_BY_SLUG_QUERYResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  content: null;
  categories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
  featuredImage: {
    alt: string | null;
    url: string | null;
  } | null;
  productGallery: Array<{
    alt: string | null;
    url: string | null;
  }> | null;
  author: {
    name: string | null;
    bio: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    image: string | null;
  } | null;
} | null;
// Variable: GET_ARTICLES_BY_CATEGORY_QUERY
// Query: *[_type == "article" && references(*[_type == "category" && slug.current == $categorySlug]._id)] | order(publishedAt desc) {    _id,    title,    "slug": slug.current,    excerpt,    publishedAt,    featuredImage {      alt,      "url": asset->url    },    // We can also pull the category names back out    categories[]-> {      title,      "slug": slug.current    },    author-> {      name    }  }
export type GET_ARTICLES_BY_CATEGORY_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  featuredImage: {
    alt: string | null;
    url: string | null;
  } | null;
  categories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
  author: {
    name: string | null;
  } | null;
}>;
// Variable: GET_ARTICLES_BY_TAG_QUERY
// Query: *[_type == "article" && references(*[_type == "tag" && slug.current == $tagSlug]._id)] | order(publishedAt desc) {    _id,    title,    "slug": slug.current,    excerpt,    publishedAt,    featuredImage {      alt,      "url": asset->url    },    categories[]-> {      title,      "slug": slug.current    },    author-> {      name    }  }
export type GET_ARTICLES_BY_TAG_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  featuredImage: {
    alt: string | null;
    url: string | null;
  } | null;
  categories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
  author: {
    name: string | null;
  } | null;
}>;
// Variable: GET_ARTICLES_BY_TYPE_QUERY
// Query: *[_type == "article" && references(*[_type == "articleType" && slug.current == $articleTypeSlug]._id)] | order(publishedAt desc) {    _id,    title,    "slug": slug.current,    excerpt,    publishedAt,    featuredImage {      alt,      "url": asset->url    },    categories[]-> {      title,      "slug": slug.current    },    author-> {      name    }  }
export type GET_ARTICLES_BY_TYPE_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  featuredImage: {
    alt: string | null;
    url: string | null;
  } | null;
  categories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
  author: {
    name: string | null;
  } | null;
}>;
// Variable: GET_ALL_CATEGORIES_QUERY
// Query: *[_type == "category"] | order(title asc) {    _id,    title,    "slug": slug.current,    description,    "imageUrl": image.asset->url,    // Optional: Get the total number of articles in each category    "articleCount": count(*[_type == "article" && references(^._id)])  }
export type GET_ALL_CATEGORIES_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  imageUrl: string | null;
  articleCount: number;
}>;
// Variable: GET_ALL_TAGS_QUERY
// Query: *[_type == "tag"] | order(title asc) {    _id,    title,    "slug": slug.current,    description,    // Bonus: Count how many articles are actually using this tag    "articleCount": count(*[_type == "article" && references(^._id)])  }
export type GET_ALL_TAGS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  articleCount: number;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "  *[_type == \"article\" && defined(publishedAt)] | order(publishedAt desc)[0...20] {\n    _id,\n    title,\n    \"slug\": slug.current,\n    excerpt,\n    publishedAt,\n    featuredImage {\n      alt,\n      \"url\": asset->url\n    },\n    categories[]-> {\n      title,\n      \"slug\": slug.current\n    },\n    productGallery[] {\n      alt,\n      \"url\": asset->url\n    },\n    author-> {\n      name\n    }\n  }": GET_RECENT_ARTICLES_QUERYResult;
    "  *[_type == \"article\" && slug.current == $slug][0] {\n    _id,\n    title,\n    \"slug\": slug.current,\n    excerpt,\n    publishedAt,\n    content, // Often needed for the full page\n    categories[]-> {\n      title,\n      \"slug\": slug.current\n    },\n    featuredImage {\n      alt,\n      \"url\": asset->url\n    },\n    productGallery[] {\n      alt,\n      \"url\": asset->url\n    },\n    author-> {\n      name,\n      bio,\n      \"image\": image.asset->url\n    }\n  }": GET_ARTICLE_BY_SLUG_QUERYResult;
    "  *[_type == \"article\" && references(*[_type == \"category\" && slug.current == $categorySlug]._id)] | order(publishedAt desc) {\n    _id,\n    title,\n    \"slug\": slug.current,\n    excerpt,\n    publishedAt,\n    featuredImage {\n      alt,\n      \"url\": asset->url\n    },\n    // We can also pull the category names back out\n    categories[]-> {\n      title,\n      \"slug\": slug.current\n    },\n    author-> {\n      name\n    }\n  }": GET_ARTICLES_BY_CATEGORY_QUERYResult;
    "  *[_type == \"article\" && references(*[_type == \"tag\" && slug.current == $tagSlug]._id)] | order(publishedAt desc) {\n    _id,\n    title,\n    \"slug\": slug.current,\n    excerpt,\n    publishedAt,\n    featuredImage {\n      alt,\n      \"url\": asset->url\n    },\n    categories[]-> {\n      title,\n      \"slug\": slug.current\n    },\n    author-> {\n      name\n    }\n  }": GET_ARTICLES_BY_TAG_QUERYResult;
    "  *[_type == \"article\" && references(*[_type == \"articleType\" && slug.current == $articleTypeSlug]._id)] | order(publishedAt desc) {\n    _id,\n    title,\n    \"slug\": slug.current,\n    excerpt,\n    publishedAt,\n    featuredImage {\n      alt,\n      \"url\": asset->url\n    },\n    categories[]-> {\n      title,\n      \"slug\": slug.current\n    },\n    author-> {\n      name\n    }\n  }": GET_ARTICLES_BY_TYPE_QUERYResult;
    "  *[_type == \"category\"] | order(title asc) {\n    _id,\n    title,\n    \"slug\": slug.current,\n    description,\n    \"imageUrl\": image.asset->url,\n    // Optional: Get the total number of articles in each category\n    \"articleCount\": count(*[_type == \"article\" && references(^._id)])\n  }": GET_ALL_CATEGORIES_QUERYResult;
    "  *[_type == \"tag\"] | order(title asc) {\n    _id,\n    title,\n    \"slug\": slug.current,\n    description,\n    // Bonus: Count how many articles are actually using this tag\n    \"articleCount\": count(*[_type == \"article\" && references(^._id)])\n  }": GET_ALL_TAGS_QUERYResult;
  }
}
